"""report_g2.py - card chat-G5: build report_g2.md from answers_g2/*.json + scores_g2/*.json. Numbers only.

Adapted from report.py (card chat-G1): same cell format, same project-file-citation regex.
PREDICTION CONTRACT: every answer file has a score file; the report lists 8 cases x 3 arms x 2 repeats.
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import protocol  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
cases = json.load(open(os.path.join(HERE, "cases_g2.json"), encoding="utf-8"))["cases"]
ARMS = ["gemini-pro", "opus-medium", "opus-high"]
AD, SD = os.path.join(HERE, "answers_g2"), os.path.join(HERE, "scores_g2")
ans, sc = {}, {}
for f in os.listdir(AD):
    a = json.load(open(os.path.join(AD, f), encoding="utf-8"))
    ans[(a["case"], a["arm"], a["rep"])] = a
    p = os.path.join(SD, f)
    if os.path.exists(p):
        sc[(a["case"], a["arm"], a["rep"])] = json.load(open(p, encoding="utf-8"))
URL = re.compile(r"https?://\S+")
LOCAL = re.compile(r"(\bdocs[/\\][\w.-]+|\btools[/\\][\w.-]+|\.agents[/\\]\S+|\.claude[/\\]\S+|NAMES\.md|peer\.ps1|"
                   r"vi-server-ids\S*|this repository|in this repo\w*|AGENTS\.md|\barchive[/\\]\S+|STATUS\.md|"
                   r"camera-acquisition-facts|com-driving)", re.I)
LOC = {k: sorted(set(m.group(0) for m in LOCAL.finditer(URL.sub("", v["answer"])))) for k, v in ans.items()}
G = {"correct": "C", "partly": "P", "wrong": "W", "unscored": "?"}
L = ["# chat-G5 - LabVIEW-focused known-answer comparison: gemini-3.1-pro-high vs Opus fact medium vs Opus fact high", "",
     "Generated by `tools/bench/gsearch/report_g2.py` from `answers_g2/*.json` + `scores_g2/*.json` (runner",
     "`tools/bench/gsearch/run_g2.py`). Cases + verifying evidence: `tools/bench/gsearch/cases_g2.json` (G1-G3 from",
     "`cases.json`, L1-L5 new). Blind scorer: claude sonnet/low thin, sees question + known answer + ONE answer under a",
     "random label. Cell = grade (C/P/W) / seconds / source URLs (primary ni.com y/n) [/ LOCAL = cites a project file].", "",
     "Arms: `gemini-pro` = peer.ps1 -Agent gemini -Model gemini-3.1-pro-high **-TimeoutSec 600** (agy --print-timeout",
     "600s; web-only brief of chat-G3 + user's deny command(*) of chat-G4); `opus-medium` = peer.ps1 -Kind fact as-is",
     "(claude-opus-5-5 effort medium, --safe-mode, plan mode, WebSearch/WebFetch); `opus-high` = the SAME call plus",
     "peer.ps1's own `-Effort high` override (DryRun: identical args except `--effort high`). Claude arms -TimeoutSec 300.", "",
     "| case | topic | " + " | ".join("%s r%d" % (a, r) for a in ARMS for r in (1, 2)) + " |",
     "|---|---|" + "---|" * 6]
missing = 0
for c in cases:
    row = [c["id"], c["topic"]]
    for a in ARMS:
        for r in (1, 2):
            k = (c["id"], a, r)
            if k not in ans:
                row.append("(missing)")
                missing += 1
                continue
            s = sc.get(k)
            if not s:
                missing += 1
            row.append("%s / %s s / %s%s%s" % (G[s["grade"]] if s else "-", ans[k]["seconds"], s["n_urls"] if s else "?",
                                               " y" if s and s["primary"] else " n", " / LOCAL" if LOC[k] else ""))
    L.append("| " + " | ".join(row) + " |")
n_cells = len(cases) * 2
L += ["", "## Totals per arm (%d answers each = %d cases x 2 repeats)" % (n_cells, len(cases)), "",
      "| arm | answered | correct | partly | wrong | unscored | primary-source rate | median s | mean s | max s | Claude usd (answers) | scorer usd |",
      "|---|---|---|---|---|---|---|---|---|---|---|---|"]
tot = 0.0
for a in ARMS:
    ks = [k for k in ans if k[1] == a]
    ss = [sc[k] for k in ks if k in sc]
    secs = sorted(ans[k]["seconds"] for k in ks if ans[k]["seconds"] is not None)
    usd = sum((ans[k]["claude_usd"] or 0.0) for k in ks)
    susd = sum((s.get("scorer_usd") or 0.0) for s in ss)
    tot += usd + susd
    n = lambda g: sum(1 for s in ss if s["grade"] == g)
    L.append("| %s | %d/%d | %d | %d | %d | %d | %d/%d | %s | %s | %s | %.4f | %.4f |" % (
        a, sum(1 for k in ks if ans[k]["outcome"] == "ANSWERED"), len(ks), n("correct"), n("partly"), n("wrong"),
        n("unscored"), sum(1 for s in ss if s["primary"]), len(ss), secs[len(secs) // 2] if secs else None,
        round(sum(secs) / len(secs), 1) if secs else None, secs[-1] if secs else None, usd, susd))
L += ["", "## Correct per arm: G1-G3 (repeat of chat-G1) vs L1-L5 (new)", "", "| arm | G1-G3 C/P/W | L1-L5 C/P/W |",
      "|---|---|---|"]
for a in ARMS:
    def cpw(ids):
        ss = [sc[k] for k in sc if k[1] == a and k[0] in ids]
        return "%d/%d/%d" % tuple(sum(1 for s in ss if s["grade"] == g) for g in ("correct", "partly", "wrong"))
    L.append("| %s | %s | %s |" % (a, cpw({"G1", "G2", "G3"}), cpw({"L1", "L2", "L3", "L4", "L5"})))
L += ["", "## Non-answers by cause", ""]
causes = {}
for k, v in sorted(ans.items()):
    if v["outcome"] != "ANSWERED" or not v["answer"].strip():
        t = v["raw_tail"]
        cause = ("agy command-permission auto-deny" if "permission" in t and "command" in t else
                 "peer.ps1 timeout" if v["outcome"] == "TIMEOUT" else
                 "driver timeout" if "driver timeout" in t else v["outcome"])
        causes.setdefault((v["arm"], cause), []).append("%s r%d" % (k[0], k[2]))
if not causes:
    L.append("- none: all %d cells ANSWERED." % len(ans))
for (a, cause), cells in sorted(causes.items()):
    L.append("- %s: %s x%d (%s)" % (a, cause, len(cells), ", ".join(cells)))
L += ["", "## Answers that cite PROJECT files", "",
      "The gemini arm now runs agy from an empty per-call temp dir (chat-G3); the claude fact cells run thin with only",
      "WebSearch/WebFetch allowed. Only answers that CITE a project file are listed.", ""]
hits = [k for k in sorted(LOC) if LOC[k]]
if not hits:
    L.append("- none.")
for k in hits:
    L.append("- %s %s r%d (%s): %s" % (k[0], k[1], k[2], sc[k]["grade"] if k in sc else "-", ", ".join(LOC[k][:6])))
L += ["", "Total Claude usd in this bench (answers + scorer): %.4f. Gemini answers cost 0 Claude usage." % tot, "",
      "## Scorer reasons (raw)", ""]
for c in cases:
    for a in ARMS:
        for r in (1, 2):
            s = sc.get((c["id"], a, r))
            if s:
                L.append("- %s %s r%d: %s - %s" % (c["id"], a, r, s["grade"], s["reason"].replace("\n", " ")[:220]))
L += ["", "## Non-answer tails (raw)", ""]
for k, v in sorted(ans.items()):
    if v["outcome"] != "ANSWERED":
        L.append("- %s %s r%d: outcome %s rc %s; tail: %s" % (k[0], k[1], k[2], v["outcome"], v["rc"],
                                                              v["raw_tail"][-200:].replace("\n", " ")))
open(os.path.join(HERE, "report_g2.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
print(protocol.result_line(protocol.make_result(len(ans) - missing, missing, None if not missing else "missing cells")))
