"""report.py - card chat-G1: build report_g1.md from answers/*.json + scores/*.json. Numbers only, no recommendation.

PREDICTION CONTRACT: every answer file has a score file; the report lists cases x arms x repeats.
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import protocol  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
cases = json.load(open(os.path.join(HERE, "cases.json"), encoding="utf-8"))["cases"]
ARMS = ["gemini", "gemini-pro", "claude"]
ans, sc = {}, {}
for f in os.listdir(os.path.join(HERE, "answers")):
    a = json.load(open(os.path.join(HERE, "answers", f), encoding="utf-8"))
    ans[(a["case"], a["arm"], a["rep"])] = a
    p = os.path.join(HERE, "scores", f)
    if os.path.exists(p):
        sc[(a["case"], a["arm"], a["rep"])] = json.load(open(p, encoding="utf-8"))
import re
URL = re.compile(r"https?://\S+")
LOCAL = re.compile(r"(\bdocs[/\\][\w.-]+|\btools[/\\][\w.-]+|\.agents[/\\]\S+|\.claude[/\\]\S+|NAMES\.md|peer\.ps1|"
                   r"vi-server-ids\S*|this repository|in this repo\w*|AGENTS\.md|\barchive[/\\]\S+)", re.I)


def local_refs(text):
    """Project-file references in an answer, URLs removed first (ni.com/docs/... is not a local ref)."""
    return sorted(set(m.group(0) for m in LOCAL.finditer(URL.sub("", text))))


LOC = {k: local_refs(v["answer"]) for k, v in ans.items()}
G = {"correct": "C", "partly": "P", "wrong": "W", "unscored": "?"}
L = ["# chat-G1 - Gemini (agy) vs claude fact role on 7 known-answer web questions", "",
     "Generated by `tools/bench/gsearch/report.py` from `answers/*.json` and `scores/*.json`. Cases and verifying",
     "evidence: `tools/bench/gsearch/cases.json`. Grades by a blind scorer (claude sonnet/low, thin; sees question,",
     "known answer and one answer under a random label). Cell = grade (C/P/W) / seconds / source URLs (primary y/n).", "",
     "Arms: `gemini` = peer.ps1 -Agent gemini (agy default model, not readable); `gemini-pro` = -Model gemini-3.1-pro-high;",
     "`claude` = peer.ps1 -Kind fact (role fact = claude-opus-5-5, effort medium, thin, WebSearch/WebFetch).", "",
     "| case | topic | " + " | ".join("%s r%d" % (a, r) for a in ARMS for r in (1, 2)) + " |",
     "|---|---|" + "---|" * 6]
missing = 0
for c in cases:
    row = ["%s" % c["id"], c["topic"]]
    for a in ARMS:
        for r in (1, 2):
            k = (c["id"], a, r)
            if k not in ans:
                row.append("(missing)")
                missing += 1
                continue
            s = sc.get(k)
            g = G[s["grade"]] if s else "-"
            if not s:
                missing += 1
            row.append("%s / %s s / %s%s%s" % (g, ans[k]["seconds"], s["n_urls"] if s else "?",
                                               " y" if s and s["primary"] else " n", " / LOCAL" if LOC[k] else ""))
    L.append("| " + " | ".join(row) + " |")
L += ["", "## Totals per arm (14 answers each = 7 cases x 2 repeats)", "",
      "| arm | answered | correct | partly | wrong | unscored | primary-source rate | median s | mean s | Claude usd (answers) | scorer usd |",
      "|---|---|---|---|---|---|---|---|---|---|---|"]
tot_usd = 0.0
for a in ARMS:
    ks = [k for k in ans if k[1] == a]
    ss = [sc[k] for k in ks if k in sc]
    secs = sorted(ans[k]["seconds"] for k in ks if ans[k]["seconds"] is not None)
    usd = sum((ans[k]["claude_usd"] or 0.0) for k in ks)
    susd = sum((s.get("scorer_usd") or 0.0) for s in ss)
    tot_usd += usd + susd
    n = lambda g: sum(1 for s in ss if s["grade"] == g)
    prim = sum(1 for s in ss if s["primary"])
    med = secs[len(secs) // 2] if secs else None
    mean = round(sum(secs) / len(secs), 1) if secs else None
    L.append("| %s | %d/%d | %d | %d | %d | %d | %d/%d | %s | %s | %.4f | %.4f |" % (
        a, sum(1 for k in ks if ans[k]["outcome"] == "ANSWERED"), len(ks), n("correct"), n("partly"), n("wrong"),
        n("unscored"), prim, len(ss), med, mean, usd, susd))
L += ["", "## Answers that cite PROJECT files (read from the repository, not the web)", "",
      "agy runs with the project root as its working directory (peer.ps1 `Set-Location $wd`), so a gemini cell can read",
      "the files where these known answers are recorded. The claude fact cell also runs from the project root (thin,",
      "--safe-mode, allow list WebSearch/WebFetch, plan mode); whether plan mode let it Read files was not measured.",
      "Only answers that CITE a project file are listed; an uncited read cannot be detected from the answer text.", ""]
for k in sorted(LOC):
    if LOC[k]:
        L.append("- %s %s r%d (%s): %s" % (k[0], k[1], k[2], sc[k]["grade"] if k in sc else "-", ", ".join(LOC[k][:6])))
L += ["", "Total Claude usd in this bench (answers + scorer): %.4f. Gemini answers cost 0 Claude usage." % tot_usd, "",
      "## Scorer reasons (raw)", ""]
for c in cases:
    for a in ARMS:
        for r in (1, 2):
            s = sc.get((c["id"], a, r))
            if s:
                L.append("- %s %s r%d: %s - %s" % (c["id"], a, r, s["grade"], s["reason"].replace("\n", " ")[:220]))
L += ["", "## Part A (headless check, before Part B)", "",
      "- `peer.ps1 -Agent gemini -Kind fact` (agy 1.2.7, default model), no peer.ps1 change: ANSWERED in 189 s, 4 URLs",
      "  (ni.com download page, forums.ni.com, ni.com docs, wikipedia); log `tools/bench/gsearch/partA_gemini.log`,",
      "  archive `archive/peer/2026-09-29-g1-partA-labview-latest.md`. agy user settings already allow `read_url(*)`",
      "  (`~/.gemini/antigravity-cli/settings.json`); no denial in that run. The answer's content was not checked.",
      "- Non-answers below: every gemini-pro ERROR is agy's `jetski: no output produced - a tool required the \"command\"",
      "  permission that headless mode cannot prompt for` (same wall as 2026-09-22); every gemini TIMEOUT is peer.ps1's",
      "  300 s -TimeoutSec (agy --print-timeout 300s).", "",
      "## Non-answers (raw)", ""]
for k, v in sorted(ans.items()):
    if v["outcome"] != "ANSWERED":
        L.append("- %s %s r%d: outcome %s rc %s; tail: %s" % (k[0], k[1], k[2], v["outcome"], v["rc"],
                                                              v["raw_tail"][-200:].replace("\n", " ")))
open(os.path.join(HERE, "report_g1.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
print(protocol.result_line(protocol.make_result(len(ans) - missing, missing, None if not missing else "missing cells")))
