r"""diag_c133_5_pred_p3b2b - card 133-5 step 2b: REGENERATE plan_ring_p3b2b_pred.json for the REBASED plan_ring_p3b2b.json
(base = the real graph of session a's SCRATCH saved file, step 2, via `stage_prerun.py --rebase`). Offline, no LabVIEW.
WHAT EXISTED: plan_ring_p3b_split_p3b2.py pred() (:218-251, card 133-3) wrote the provisional pred; this file applies the SAME
fields to the rebased plan (census_predict.predict over census_samples.json, ops = compile_plan, memory_pred =
stage_prerun.x10_model_peak with checkpoints {0,len}|BIND), start = stage_prerun.x10_start(<a-file md5>) = the MEASURED load
of a's file (memory_model.json load_by_vi) + op-0 read. bed / bed_md5 from the rebased base graph's own vi/md5; Error List base
= P3b-1's measured expected file; readback carried from the provisional pred.
PREDICTION: Q1 plan final, rebased (not provisional), base md5 == the a-file graph's md5 field; Q2 ops == compile (18 actions);
Q3 start from load_by_vi (not the 570 fallback); X10 peak <= 690; Q4 pred written, plan md5 == file.
    py tools/bgrun.py --material --max-min 3 --log tools/bench/diag_c133_5_pred_p3b2b.log -- py -u tools/bench/diag_c133_5_pred_p3b2b.py"""
import hashlib, json, os, sys                                                       # noqa: E401
B = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(B))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import protocol as P, stagexec as SX, census_predict as CPR, stage_prerun as SPR   # noqa: E402,E401
md5 = lambda p: hashlib.md5(open(p, "rb").read()).hexdigest()                    # noqa: E731
rel = lambda p: os.path.relpath(p, ROOT).replace("\\", "/")                       # noqa: E731
J = lambda p: json.load(open(p if os.path.isabs(p) else os.path.join(ROOT, p), encoding="utf-8"))   # noqa: E731
ok, arts = [], []


def gate(name, c, det=""):
    ok.append((name, bool(c)))
    print("{0}  {1}  {2}".format("PASS" if c else "FAIL", name, str(det)[:1200]), flush=True)


PB = os.path.join(B, "plan_ring_p3b2b.json")
PROV = os.path.join(B, "plan_ring_p3b2b_pred_provisional_c133_5.json")
EXP1 = os.path.join(B, "errorlist_expected_D1_ring_p3b1_20261002_060910.json")
SUM = J(os.path.join(B, "stage_d1_ring_p3b2a_scratch_sum.json"))
pl = J(PB)
fz = pl["finalized"]
g = J(fz["base"]["path"])
gate("Q1 plan final, rebased, base md5 == file, base vi md5 == a's scratch file md5",
     pl.get("final") is True and not (fz["base"].get("sim_of") or g.get("sim_of")) and md5(os.path.join(ROOT, fz["base"]["path"])) == fz["base"]["md5"]
     and g.get("md5") == SUM["final_md5"], (fz["base"], g.get("md5"), SUM["final_md5"]))
MODEL = SPR.load_memory_model()
st = SPR.x10_start(g.get("md5"), MODEL)
gate("Q3 X10 start from the MEASURED load of a's file (memory_model load_by_vi), not the 570 fallback", st is not None, st)
start, cite = st or (None, None)
SAMP, E1 = J(os.path.join(B, "census_samples.json")), J(EXP1)
end = J(fz["step_files"][-1]["path"])["state"]
dd = dict(("new:" + a["as"], a["id"]) for a in pl["actions"] if a["op"] == "create" and a.get("as"))
born = dict((int(u), dd.get(s)) for s, u in end["sym"].items())
bo = set(int(r["owner_uid"]) for r in g["terminals"])
unw = sorted("{0} '{1}' ({2} #{3})".format(born.get(int(r["owner_uid"]), "?"), r["term_name"], r["owner_class"], r["owner_uid"])
             for r in end["terminals"] if int(r["owner_uid"]) not in bo and not r["is_source"] and not r["wire_uid"])
rep = CPR.predict(pl, {}, SAMP)
ops = SX.compile_plan(pl)
gate("Q2 ops == compile, each of the {0} actions once".format(len(pl["actions"])),
     sorted(n for o in ops for n in o["acts"]) == list(range(1, len(pl["actions"]) + 1)), len(ops))
bind = sorted(k for k, o in enumerate(ops, 1) if o["kind"] in SX.BIND_KINDS)
cps = sorted(set([0, len(ops)]) | set(bind))
mp = SPR.x10_model_peak([o["kind"] for o in ops], cps, model=MODEL, start_mb=start)
el = {"bed_total": E1["total"], "removed": {}, "new_items_predicted": 0, "predicted_total": E1["total"], "base_file": rel(EXP1),
      "unwired_created_sinks": unw, "checked": True,
      "class_range": "tools/bench/errorlist_expect_p3b2ab.json (plan_ring_p3b_split_p3b2.py S7) - the step's FINAL file only (session b)"}
d = {"schema": "ring-p3b-pred/1", "card": "133-5", "note": "P3b-2 session b (PD283(c)); base = REAL graph of session a's SCRATCH saved file "
     "(card 133-5 step 2) after stage_prerun --rebase; regenerated by tools/bench/diag_c133_5_pred_p3b2b.py",
     "plan": {"path": rel(PB), "md5": md5(PB)}, "graph": {"path": fz["base"]["path"], "md5": fz["base"]["md5"]},
     "bed": g.get("vi"), "bed_md5": g.get("md5"), "census": dict(rep["derived"]), "census_overall": rep["overall"],
     "census_unpredicted": [pl["actions"][k - 1]["id"] for k in rep["unpredicted"]],
     "census_rows": [dict((k, r[k]) for k in ("k", "id", "op", "variant", "delta", "verdict")) for r in rep["rows"]],
     "ops": [o["kind"] for o in ops], "cdiff_rows": sorted(fz["end_cdiff_rows"]), "errorlist": el,
     "readback": J(PROV).get("readback"),
     "memory_pred": {"card": "133-5", "checkpoints": cps, "R": mp["R"], "N": mp["N"], "bind_ops": bind, "op_kinds": [o["kind"] for o in ops],
                     "start_mb": mp["start_mb"], "start_cite": cite, "peak_mb": mp["peak_mb"], "fail_above_mb": mp["fail_above_mb"],
                     "below_fail": mp["ok"], "model": {"path": rel(SPR.MEMORY_MODEL), "md5": md5(SPR.MEMORY_MODEL)},
                     "how": "stage_prerun.x10_model_peak on the compiled plan, checkpoints {0, len} | BIND, measured start of the input VI"},
     "summary": {"path": fz["summary"]["path"], "md5": fz["summary"]["md5"]}}
po = os.path.join(B, "plan_ring_p3b2b_pred.json")
json.dump(d, open(po, "w", encoding="utf-8"), indent=1)
arts.append({"path": rel(po), "md5": md5(po)})
print("  FACT  X10 b: N {0} R {1} start {2} ({3}) peak {4} (fail above {5}); census {6} unpredicted {7}".format(
    mp["N"], mp["R"], mp["start_mb"], cite, mp["peak_mb"], mp["fail_above_mb"], d["census"], d["census_unpredicted"]), flush=True)
gate("Q3b X10 peak <= 690", mp["ok"], mp["peak_mb"])
gate("Q4 pred written, keyed to the plan file", J(po)["plan"]["md5"] == md5(PB), arts)
np_, nf = sum(1 for _n, c in ok if c), sum(1 for _n, c in ok if not c)
print(P.result_line(P.make_result(np_, nf, next((n for n, c in ok if not c), None), arts)), flush=True)
sys.exit(1 if nf else 0)
