r"""prep_c140_3_mkv15 - card 140-3 item 2 (offline, no LabVIEW, no COM). PD321(b)(d): v15 = v14 with ops 2-3
(`p4_do_10171` delete_object #10171, `p4_rle_w23255` RLE w23255) replaced by `p4_dw_23255` delete_wire w23255 THEN `p4_do_10171`;
top-level base WITHOUT the stale `provisional`/`sim_of`; `finalized` POPPED and regenerated by the existing finalize path
stagesim.simulate (never copied, PD313(c)); meta15 = meta14 with the same swap in its actions list.
Prior art: tools/bench/prep_c139_p1_mkv10.py (finalize path :203-227, replay + end gates :233-254, compile + route compare by action
id :256-277 - copied); prep_c139_6_mkv14.py (meta walk); prep_c140_3_gate.py (PD321(b) gate, PASS 3/0, prep_c140_3_gate.log).
PREDICTION CONTRACT:
  M0 input md5 == card (v14 22f58271, meta14 29f6535b, graph 50595c62);  G1 every sink of w23255 is a #10171 terminal (re-checked);
  A15 185 actions; removed exactly p4_rle_w23255, added exactly p4_dw_23255 at position 2, p4_do_10171 at 3, every other action identical
     and in v14 order;  V v15_in validates, base has no provisional/sim_of;
  S simulate returned; v15 actions == A15; fs_routes regenerated (every key's action id == stored id); replay END (186 steps, no error);
  E end cdiff rows == v14 finalized end_cdiff_rows (24); PS per-step cdiff == v14's at every shared id except the 3 changed ids;
  C compile_plan ALL: v15 ops == v14 ops (one op replaced by one); route compare v14->v15 differs only on keys holding a changed id;
  RC route_check PASS; MT meta15 written, every v15 id stepped, p4_dw_23255 step 1 session 1.1; v14/meta14 untouched.
    py tools/bgrun.py --material --max-min 20 --log tools/bench/prep_c140_3_mkv15.log -- py -u tools/bench/prep_c140_3_mkv15.py"""
import copy, hashlib, json, os, shutil, sys, traceback                                     # noqa: E401
ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "tools"))
from tools import protocol  # noqa: E402
import stagesim as SS, stagexec as SX                                                       # noqa: E402,E401
B = os.path.join(ROOT, "tools", "bench")
V14, META14 = os.path.join(B, "plan_ring_p4_v14.json"), os.path.join(B, "plan_ring_p4_v14_meta.json")
V15IN, V15, META15 = os.path.join(B, "plan_ring_p4_v15_in.json"), os.path.join(B, "plan_ring_p4_v15.json"), os.path.join(B, "plan_ring_p4_v15_meta.json")
GRAPH = os.path.join(B, "graph_ring_p3b2b_20261002_133824.json")
SIMDIR = os.path.join(B, "sim", "ring_p4_v15")
WANT = {V14: "22f582715e3d303ea0625fbe98bb590e", META14: "29f6535b1f280b3a33a07dbdeeff8893", GRAPH: "50595c62d0332a94bf066538cf20c0ae"}
DW = {"op": "delete_wire", "id": "p4_dw_23255", "wire_uid": 23255,
      "why": ("ROUTE delete_wire | MEASURED | PD321(b): w23255 (tunnel #23417 inner -> #10171 x,y; graph: its only 2 sinks are #10171's, "
              "prep_c140_3_gate.log) deleted BEFORE #10171 instead of RLE after it (RLE -> error 1055, diag_c140_2_scratch.log:72-75); "
              "delete_wire route = op 1 p4_dw_23310 (launched P2a)")}
CHG = {"p4_dw_23255", "p4_do_10171", "p4_rle_w23255"}
md5 = lambda p: hashlib.md5(open(p, "rb").read()).hexdigest()                             # noqa: E731
rel = lambda p: os.path.relpath(p, ROOT).replace("\\", "/")                                # noqa: E731
J = lambda p: json.load(open(p if os.path.isabs(p) else os.path.join(ROOT, p), encoding="utf-8"))   # noqa: E731
G, ARTS = {"pass": 0, "fail": 0, "first": None}, []


def gate(label, ok, d=""):
    G["pass" if ok else "fail"] += 1
    if not ok and G["first"] is None:
        G["first"] = label
    print("GATE {0} | {1} | {2}".format("PASS" if ok else "FAIL", label, str(d)[:700]), flush=True)
    return ok


def done():
    print(protocol.result_line(protocol.make_result(G["pass"], G["fail"], G["first"], ARTS)), flush=True)
    sys.exit(0 if not G["fail"] else 1)


def sig(o):
    return json.dumps(dict((k, v) for k, v in o.items() if k not in ("acts", "in_act", "out_act", "of_act")), sort_keys=True, default=str)


def by_ids(ops, A):
    return dict((tuple(A[n - 1]["id"] for n in o["acts"]), sig(o)) for o in ops)


gate("M0 input md5 == card", all(md5(p) == w for p, w in WANT.items()), dict((os.path.basename(p), md5(p)) for p in WANT))
if G["fail"]:
    done()
gr = J(GRAPH)
sinks = [r for r in gr["terminals"] if r.get("wire_uid") == 23255 and not r.get("is_source")]
gate("G1 every sink of w23255 is a #10171 terminal (PD321(b) gate)", bool(sinks) and all(r.get("owner_uid") == 10171 for r in sinks),
     [(r.get("owner_uid"), r.get("term_name")) for r in sinks])
v14 = J(V14)
A14 = v14["actions"]
ids14 = [a["id"] for a in A14]
d14 = dict((a["id"], a) for a in A14)
gate("A0 v14 #2 == p4_do_10171, #3 == p4_rle_w23255", ids14[1:3] == ["p4_do_10171", "p4_rle_w23255"], ids14[:4])
if G["fail"]:
    done()
A15 = [copy.deepcopy(A14[0]), copy.deepcopy(DW), copy.deepcopy(A14[1])] + [copy.deepcopy(a) for a in A14[3:]]
ids15 = [a["id"] for a in A15]
removed = [i for i in ids14 if i not in ids15]
added = [i for i in ids15 if i not in d14]
same = [i for i in ids15 if i in d14]
gate("A15 185 actions; removed == [p4_rle_w23255]; added == [p4_dw_23255] at #2; p4_do_10171 at #3; every kept action identical, v14 order",
     len(A15) == 185 and removed == ["p4_rle_w23255"] and added == ["p4_dw_23255"] and ids15[1:3] == ["p4_dw_23255", "p4_do_10171"]
     and all(dict((a["id"], a) for a in A15)[i] == d14[i] for i in same) and same == [i for i in ids14 if i in same], (len(A15), removed, added))
raw = copy.deepcopy(v14)
raw["actions"] = A15
raw["base"] = {"path": v14["base"]["path"], "md5": v14["base"]["md5"]}
raw["goal"] = ("P4 v15 (card 140-3, PD321(b)(d)): v14 22f58271 with ops 2-3 -> delete_wire w23255 then delete_object #10171 (RLE w23255 "
               "dropped); base not provisional; fs_routes regenerated by stagesim; never launched")
raw.pop("finalized", None)
raw.pop("final", None)
json.dump(raw, open(V15IN, "w", encoding="utf-8"), indent=1, default=str)
okv, whyv = protocol.validate_obj(J(V15IN))
gate("V v15_in validates (stageplan/1); base has no provisional/sim_of", okv and set(J(V15IN)["base"]) == {"path", "md5"}, whyv)
if G["fail"]:
    done()
os.makedirs(SIMDIR, exist_ok=True)
S = None
try:
    S = SS.simulate(V15IN, GRAPH, out_root=SIMDIR, plan_out_dir=SIMDIR)
except Exception as e:                                                                          # noqa: BLE001
    print("SIM EXCEPTION", type(e).__name__, e)
    traceback.print_exc()
gate("S simulate returned", S is not None)
if S is None:
    done()
po = S["plan_out"]["path"]
po = po if os.path.isabs(po) else os.path.join(ROOT, po)
shutil.copyfile(po, V15)
v15 = J(V15)
fz = v15.get("finalized") or {}
fr = fz.get("fs_routes") or {}
bad = [(k, r.get("id"), A15[int(k) - 1]["id"]) for k, r in fr.items() if A15[int(k) - 1]["id"] != r.get("id")]
print("SIM plan_out", rel(po), md5(po), "| FS_ROUTES v15", dict((k, (r["id"], r["how"])) for k, r in fr.items()))
gate("S2 v15 actions == A15; fs_routes regenerated (every key's action id == stored id); top base not provisional",
     v15["actions"] == A15 and bool(fr) and not bad and not (v15.get("base") or {}).get("provisional"), {"bad": bad, "base": v15.get("base")})
steps = S.get("steps") or []
errs = [s for s in steps if s.get("error")]
print("SIM final={0} failed={1} steps={2} first stop {3}".format(S.get("final"), S.get("failed"), len(steps),
      (errs[0].get("n"), errs[0].get("id"), str(errs[0].get("error"))[:500]) if errs else "none (END)"))
gate("R replay END (base + 185 steps, no error)", not errs and len(steps) == len(A15) + 1, len(steps))
end, end14 = set(S.get("end_cdiff_rows") or []), set((v14.get("finalized") or {}).get("end_cdiff_rows") or [])
gate("E end cdiff rows == v14's ({0})".format(len(end14)), end == end14 and len(end14) == 24, sorted(end ^ end14))
s14 = J((v14.get("finalized") or {}).get("summary", {}).get("path"))
c14 = dict((s.get("id"), s.get("cdiff_rows")) for s in (s14.get("steps") or []))
dif = [(s.get("n"), s.get("id"), len(c14.get(s.get("id")) or []), len(s.get("cdiff_rows") or [])) for s in steps
       if s.get("id") in c14 and s.get("id") not in CHG and c14[s.get("id")] != s.get("cdiff_rows")]
for s in steps[:5]:
    print("STEP", s.get("n"), s.get("op"), s.get("id"), "cdiff", len(s.get("cdiff_rows") or []), "| v14", len(c14.get(s.get("id")) or []))
gate("PS per-step cdiff == v14's at every shared id except the 3 changed ids", not dif, dif[:6])
rc = fz.get("route_check") or {}
print("FINALIZED final", v15.get("final"), "open_rows_match", fz.get("open_rows_match"), "route_check", rc.get("status"), str(rc.get("first_fail"))[:300])
gate("RC route_check PASS", rc.get("status") == "PASS", rc.get("first_fail"))
try:
    o14, o15 = SX.compile_plan(v14), SX.compile_plan(v15)
except SX.ExecStop as e:
    gate("C compile_plan v14/v15", False, e)
    done()
m14, m15 = by_ids(o14, A14), by_ids(o15, A15)
diffs = sorted(set(k for k in set(m14) | set(m15) if m14.get(k) != m15.get(k)))
other = [k for k in diffs if not set(k) & CHG]
for k in diffs:
    print("ROUTE-DIFF", "CHANGED" if k not in other else "OTHER", k, "| v14", m14.get(k), "| v15", m15.get(k))
gate("C compile ALL: v15 ops ({0}) == v14 ops ({1}); every action compiled once".format(len(o15), len(o14)),
     len(o15) == len(o14) and sorted(n for o in o15 for n in o["acts"]) == list(range(1, len(A15) + 1)), (len(o14), len(o15)))
gate("RD route compare v14->v15: every differing route holds a changed id", not other, other[:6])
meta = J(META14)
ma = meta["actions"]
mi = [x["id"] for x in ma]
gate("MT0 meta14 actions hold p4_do_10171 then p4_rle_w23255 adjacent", mi.index("p4_rle_w23255") == mi.index("p4_do_10171") + 1)
k = mi.index("p4_do_10171")
dwm = dict(copy.deepcopy(ma[k]), id="p4_dw_23255", xkind="delete_wire", cite=DW["why"][len("ROUTE delete_wire | MEASURED | "):] + " [v15]")
meta15 = copy.deepcopy(meta)
meta15["actions"] = ma[:k] + [dwm, copy.deepcopy(ma[k])] + ma[k + 2:]
meta15["recut_c140_3"] = {"from_md5": md5(META14), "plan": "plan_ring_p4_v15.json", "removed": ["p4_rle_w23255"], "added": ["p4_dw_23255"],
                          "why": "PD321(b): delete_wire w23255 before delete_object #10171 (RLE after the delete hit error 1055, diag_c140_2_scratch.log:72-75)"}
json.dump(meta15, open(META15, "w", encoding="utf-8"), indent=1)
st = {}


def walk(o):
    if isinstance(o, dict):
        if "id" in o and "step" in o and "unit" in o:
            st[o["id"]] = (o["step"], o.get("session"))
        for v in o.values():
            walk(v)
    elif isinstance(o, list):
        for v in o:
            walk(v)


walk(J(META15))
gate("MT meta15: every v15 id stepped; p4_dw_23255 step 1 session 1.1; p4_rle_w23255 gone from actions",
     all(i in st for i in ids15) and st.get("p4_dw_23255") == (1, "1.1") and "p4_rle_w23255" not in [x["id"] for x in meta15["actions"]],
     [i for i in ids15 if i not in st][:6])
gate("U v14 / meta14 untouched", md5(V14) == WANT[V14] and md5(META14) == WANT[META14])
ARTS.extend({"path": rel(p), "md5": md5(p)} for p in (V15, V15IN, META15))
done()
